apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: mainnet
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.72.0-rc1'
  dependsOn:
    - name: mirror
      namespace: common
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: false
    timeout: 25m
  timeout: 48h
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  values:
    importer:
      enabled: false
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "MAINNET"
        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_ENTITY_PERSIST_TRANSACTIONHASH: "true"
        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_SIDECAR_ENABLED: "true"
        HEDERA_MIRROR_IMPORTER_START_DATE: "1970-01-01T00:00:00.000000000Z"
    monitor:
      enabled: false
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "MAINNET"
        HEDERA_MIRROR_MONITOR_PUBLISH_SCENARIOS_PINGER_PROPERTIES_TOPICID: "0.0.798453"
        HEDERA_MIRROR_MONITOR_SUBSCRIBE_GRPC_HCS_TOPICID: "0.0.798453"
      prometheusRules:
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    grpc:
      enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
    rosetta:
      enabled: false
      env:
        HEDERA_MIRROR_ROSETTA_NETWORK: "mainnet"
    web3:
      enabled: false
