# SPDX-License-Identifier: Apache-2.0

importer:
  env:
    HIERO_MIRROR_IMPORTER_BLOCK_NODES_0_ENDPOINTS_0_HOST: "block-node-1.${SOLO_NAMESPACE}.svc.cluster.local"
    SPRING_PROFILES_ACTIVE: "blocknode"
