hedera:
  mirror:
    importer:
      generator:
        record:
          enabled: true
          transactions_per_file: 200
      downloader:
        balance:
          enabled: false
        record:
          enabled: false
