# SPDX-License-Identifier: Apache-2.0

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: rest-java

alertmanager:
  inhibitRules:
    enabled: false
    InhibitAllWhenPodIssues:
      enabled: true
      matches:
        - sourceMatch:
            - name: area
              value: resource
          targetMatch:
            - name: application
              value: rest-java
          equal:
            - namespace
            - pod

annotations: {}

config: {}

# Environment variables to add to the container. The value can either be a string or an EnvVarSource. Evaluated as a template.
env:
  SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/usr/etc/hiero/"
  # FOO:
  #   valueFrom:
  #     secretKeyRef:
  #       name: "{{ .Release.Name }}-custom"
  #       key: BAR

# Add config maps or secrets as environment variables. Evaluated as a template.
envFrom: []
# - secretRef:
#     name: "{{ .Release.Name }}-env"

fullnameOverride: ""

gateway:
  gcp:
    backendPolicy:
      connectionDraining:
        drainingTimeoutSec: 10
      logging:
        enabled: false
      sessionAffinity:
        type: CLIENT_IP
      timeoutSec: 15
    enabled: true
    healthCheckPolicy:
      config:
        httpHealthCheck:
          port: 8084
          requestPath: "{{ .Values.readinessProbe.httpGet.path }}"
        type: HTTP
      healthyThreshold: 1
  rules:
    - backendRefs:
        - group: "{{ .Values.gateway.target.group }}"
          kind: "{{ .Values.gateway.target.kind }}"
          name: "{{ include \"hedera-mirror-rest-java.fullname\" $ }}"
          port: 80
      matches: |
        {{- if .Values.routes.hooks }}
        - path:
            type: RegularExpression
            value: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/hooks'
        - path:
            type: RegularExpression
            value: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/hooks/(0|[1-9]\d*)/storage'
        {{- end }}
        - path:
            type: RegularExpression
            value: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/(allowances/nfts|airdrops)'
        - path:
            type: PathPrefix
            value: '/api/v1/network/'
        - path:
            type: RegularExpression
            value: '/api/v1/topics/(\d+\.){0,2}\d+$'
  target:
    group: ""
    kind: Service

global:
  config: {}
  env: {}
  gateway:
    enabled: false
    hostnames: []
  image: {}
  middleware: false
  namespaceOverride: ""
  podAnnotations: {}

hpa:
  behavior: {}
  enabled: false
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  minReplicas: 1

image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: gcr.io
  repository: mirrornode/hedera-mirror-rest-java
  tag: ""  # Defaults to the chart's app version

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: '{{ include "hedera-mirror-rest-java.namespace" . }}-{{ include "hedera-mirror-rest-java.fullname" . }}@kubernetescrd'
    traefik.ingress.kubernetes.io/router.pathmatcher: 'PathRegexp'
  enabled: true
  hosts:
    - host: ""
      paths:
        # the rest of /api/v1/* is still handled by the Node.js based REST API logic, except for these paths
        - path: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/(allowances/nfts|airdrops)'
        - path: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/hooks'
          condition: '{{ .Values.routes.hooks }}'
        - path: '/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/hooks/(0|[1-9]\d*)/storage'
          condition: '{{ .Values.routes.hooks }}'
        - path: '/api/v1/network/'
          type: Prefix
        - path: '/api/v1/topics/(\d+\.){0,2}\d+$'
  tls:
    enabled: false
    secretName: ""

labels: {}

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 2

middleware:
  - circuitBreaker:
      expression: NetworkErrorRatio() > 0.10 || ResponseCodeRatio(500, 600, 0, 600) > 0.25
  - retry:
      attempts: 3
      initialInterval: 100ms

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podDisruptionBudget:
  enabled: false
  # maxUnavailable: 0
  minAvailable: 50%

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

priorityClassName: ""

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 0
  timeoutSeconds: 2

# Only set if HPA is disabled
# replicas: 1

resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 1
    memory: 1024Mi

revisionHistoryLimit: 3

routes:
  hooks: false

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

service:
  annotations: {}
  port: 80
  type: ClusterIP

serviceAccount:
  create: true
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

serviceMonitor:
  enabled: false
  interval: 30s

startupProbe:
  failureThreshold: 120
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 0
  periodSeconds: 1
  timeoutSeconds: 2

terminationGracePeriodSeconds: 60

test:
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  enabled: true
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    repository: postman/newman
    tag: 6.1.3-alpine
  postman: ""  # Custom postman.json in base64 encoding
  priorityClassName: ""

tolerations: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 10%
    maxUnavailable: 25%

# Volumes to add to the container. The key is the volume name and the value is the volume mount definition. The same keys should also appear in volumes below.
volumeMounts:
  config:
    mountPath: /usr/etc/hiero
  temp:
    mountPath: /tmp

# Volume mounts to add to the container. The key is the volume name and the value is the volume definition. Evaluated as a template.
volumes:
  config:
    secret:
      defaultMode: 420
      secretName: '{{ include "hedera-mirror-rest-java.fullname" . }}'
  temp:
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi
