apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: common
spec:
  chart:
    spec:
      chart: hedera-mirror-common
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      version: '0.72.0-rc1'
  dependsOn:
    - name: testkube
      namespace: testkube
  install:
    crds: CreateReplace
  interval: 1m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 10
  values:
    testkube:
      enabled: true
      test:
        target:
          namespace: mainnet
