# SPDX-License-Identifier: Apache-2.0

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: grpc

annotations: {}

config: {}

# Environment variables to add to the container. The value can either be a string or an EnvVarSource. Evaluated as a template.
env:
  SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/usr/etc/hiero/"
  # FOO:
  #   valueFrom:
  #     secretKeyRef:
  #       name: '{{ .Release.Name }}-custom'
  #       key: BAR

# Add config maps or secrets as environment variables. Evaluated as a template.
envFrom: []
# - secretRef:
#     name: '{{ .Release.Name }}-env'

fullnameOverride: ""

gateway:
  gcp:
    backendPolicy:
      connectionDraining:
        drainingTimeoutSec: 10
      logging:
        enabled: false
      sessionAffinity:
        type: CLIENT_IP
      timeoutSec: 15
    streamingBackendPolicy:
      connectionDraining:
        drainingTimeoutSec: 10
      logging:
        enabled: false
      sessionAffinity:
        type: CLIENT_IP
      timeoutSec: 9999999
    enabled: true
    healthCheckPolicy:
      config:
        httpHealthCheck:
          port: 8081
          requestPath: "{{ .Values.readinessProbe.httpGet.path }}"
        type: HTTP
      healthyThreshold: 1
  rules:
    - backendRefs:
        - group: "{{ .Values.gateway.target.group }}"
          kind: "{{ .Values.gateway.target.kind }}"
          name: "{{ include \"hedera-mirror-grpc.fullname\" $ }}-streaming"
          port: 5600
      matches:
        - method:
            service: com.hedera.mirror.api.proto.ConsensusService
    - backendRefs:
        - group: "{{ .Values.gateway.target.group }}"
          kind: "{{ .Values.gateway.target.kind }}"
          name: "{{ include \"hedera-mirror-grpc.fullname\" $ }}"
          port: 5600
      matches:
        - method:
            service: com.hedera.mirror.api.proto.NetworkService
        - method:
            service: grpc.reflection.v1alpha.ServerReflection
        - method:
            service: grpc.reflection.v1.ServerReflection
  target:
    group: ""
    kind: Service

global:
  config: {}
  env: {}
  gateway:
    enabled: false
    hostnames: []
  image: {}
  middleware: false
  namespaceOverride: ""
  podAnnotations: {}

hpa:
  behavior: {}
  enabled: false
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  minReplicas: 1

image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: gcr.io
  repository: mirrornode/hedera-mirror-grpc
  tag: ""  # Defaults to the chart's app version

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: '{{ include "hedera-mirror-grpc.namespace" . }}-{{ include "hedera-mirror-grpc.fullname" . }}@kubernetescrd'
  enabled: true
  hosts:
    - host: ""
      paths:
        - "/com.hedera.mirror.api.proto.ConsensusService"
        - "/com.hedera.mirror.api.proto.NetworkService"
        - "/grpc.reflection.v1alpha.ServerReflection"
        - "/grpc.reflection.v1.ServerReflection"
  tls:
    enabled: false
    secretName: ""

labels: {}

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 2

middleware:
  - circuitBreaker:
      expression: NetworkErrorRatio() > 0.10 || ResponseCodeRatio(500, 600, 0, 600) > 0.25
  - retry:
      attempts: 3
      initialInterval: 250ms

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podDisruptionBudget:
  enabled: false
  # maxUnavailable: 0
  minAvailable: 50%

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

priorityClassName: ""

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 0
  timeoutSeconds: 2

# Only set if HPA is disabled
# replicas: 1

resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 128Mi

revisionHistoryLimit: 3

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

service:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  port: 5600
  type: ClusterIP

serviceAccount:
  create: true
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

serviceMonitor:
  enabled: false
  interval: 30s

startupProbe:
  failureThreshold: 120
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 0
  periodSeconds: 1
  timeoutSeconds: 2

terminationGracePeriodSeconds: 60

tolerations: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 10%
    maxUnavailable: 25%

# Volumes to add to the container. The key is the volume name and the value is the volume mount definition. The same keys should also appear in volumes below.
volumeMounts:
  config:
    mountPath: /usr/etc/hiero

# Volume mounts to add to the container. The key is the volume name and the value is the volume definition. Evaluated as a template.
volumes:
  config:
    secret:
      defaultMode: 420
      secretName: '{{ include "hedera-mirror-grpc.fullname" . }}'
