---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgBeRfW4IUHPs+VaV8OV0y8pwONyfc1yOV4KtNIGLT48A0m2zs72qD+fQyZyjhrEXsPcB4YdEVUlQwVKxUcFhcn+SvulD7Kw5ngo9GTxnY41oItcppERaG0b+NV80uV5nstk0bbuaMzZg1myZY3mwUwogYFGyWcqGYCvp4vp57/EOf1y1LUZLQYOBm+TBe1a6vqu6GHVfQNu69KnFtMTGyosoFh3hb+joz4yH6lYycvHcQXk5gjH2ktdthAsPgEEFuvRNR/ZFN8Np1bIN0LNgxoYu42Vuji58xFi/NwxwoB7Rp1I37cLDTd4UJXqJrPiCbgTz12sNQkSsNhnWxBn61mEGH4RKPjU6bQ/0HueptcD0VYVX0nHlJa+oNmJw53Re5eEgFekzKQeiBsfLz3NMBAKVATXuV4iOyGfCZL1fu3KA2mtT4VrAEKQo2bfEsqVikQnD1HLQ7wx6/Ninv7meV8fICw8A3sPECNQg0KecFtPkWrJe9mAh6zSbJNcLcqxMgEAgocKUE8cIph14V4Qrf6GHjTA/++WBWcy0k9uDzFSbLgbtt3qN/Ny17NpYklWS5n8RfSP+wmQNnmFSU2bTIX2DmvWrXMPx008EJ5CTR7UpLLKfoKmqHkvwy1iE7bcuGs2h3/sa8dniNG2WhJY6+pzcA8xwL5XA1HJFs0rlea2LE+MDtz5pqPpUKxPazCuxEWdNTpyWdE35azZQABXnDNSxPiXZrrnIF5UMuVVXYUAQdaMIrkUIB482qQamMKkdMNx5xoD+Vg=
  template:
    metadata:
      name: mirror
      namespace: common
    type: Opaque
