# SPDX-License-Identifier: Apache-2.0

{{ if and .Values.testkube.enabled .Values.testkube.prometheus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-mirror-common.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-common.fullname" . }}-test-prometheus
  namespace: {{ .Values.testkube.namespace }}
stringData:
  K6_PROMETHEUS_RW_PASSWORD: {{ .Values.testkube.prometheus.password | quote }}
  K6_PROMETHEUS_RW_SERVER_URL: {{ .Values.testkube.prometheus.serverUrl | quote }}
  K6_PROMETHEUS_RW_USERNAME: {{ .Values.testkube.prometheus.username | quote }}
{{- end }}
