# SPDX-License-Identifier: Apache-2.0

addressBook: ""  # Base64 encoded contents of a bootstrap address book

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: importer

annotations: {}

config:
  hiero:
    mirror:
      importer:
        db:
          loadBalance: false

# Environment variables to add to the container. The value can either be a string or an EnvVarSource. Evaluated as a template.
env:
  SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/usr/etc/hiero/"
  # FOO:
  #   valueFrom:
  #     secretKeyRef:
  #       name: '{{ .Release.Name }}-custom'
  #       key: BAR

# Add config maps or secrets as environment variables. Evaluated as a template.
envFrom: []
# - secretRef:
#     name: '{{ .Release.Name }}-env'

fullnameOverride: ""

global:
  config: {}
  env: {}
  image: {}
  namespaceOverride: ""
  podAnnotations: {}

image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: gcr.io
  repository: mirrornode/hedera-mirror-importer
  tag: ""  # Defaults to the chart's app version

labels: {}

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 2

nameOverride: ""

networkPolicy:
  enabled: false

nodeSelector: {}

podAnnotations:
  "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"

podDisruptionBudget:
  enabled: false
  # maxUnavailable: 0
  minAvailable: 1

podMonitor:
  enabled: false
  interval: 30s

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

priorityClassName: ""

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 0
  timeoutSeconds: 2

replicas: 1

resources:
  limits:
    cpu: 4
    memory: 5Gi
  requests:
    cpu: 4
    memory: 5Gi

revisionHistoryLimit: 3

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

serviceAccount:
  create: true
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

startupProbe:
  failureThreshold: 8640
  httpGet:
    path: /actuator/health/startup
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 2

terminationGracePeriodSeconds: 30

tolerations: []

updateStrategy:
  type: Recreate

# Volumes to add to the container. The key is the volume name and the value is the volume mount definition. The same keys should also appear in volumes below.
volumeMounts:
  config:
    mountPath: /usr/etc/hiero
  temp:
    mountPath: /tmp

# Volume mounts to add to the container. The key is the volume name and the value is the volume definition. Evaluated as a template.
volumes:
  config:
    secret:
      defaultMode: 420
      secretName: '{{ include "hedera-mirror-importer.fullname" . }}'
  temp:
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi
