---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgACOZbRqDxSKUg/atmtlZZgPNhR5iec4tJ6puSLGtKzGYduzladUALXoruYV5velx14ffU0aZQH6k/YErJGxhcUjBrjqVsKNVafmGIvTjcV5io8jhv+Xbuei6wOWwtj/+S/8u80C16hd5Wdiq6S7metLJ9ttNR/fD7xaPaa/tqdvhZABgLZzX8oOnv0IToLFbOawKvp3E4mHeVGrHXfWJDROgFBmSAhTlSoF5PnXQSjCbK2Clfz7HONQrdr4+n6iglTXY3m8GhPhMkoKKv2oJt4+ocwTRgcSI8mxObUndYcIp4rmVStO4peluMxd94chWlZsmqKN85eApkJRoc9lHZklxbXGyDpLuvk6F2kN/nY19tFRbg0NZPmPRmyr5jn3KUXS7w1eDp+vhs0ims9QGDQSP2JCzgmw2LNsJmRBQenxPiGjyt6kiy3ojfxL6K60qUyEAMyd+h1sOWycD+ZeVFMJ1q0MRvJxdn6TMqXb88fwO0rBATb1rOA530BwfwvSs7VjWFrxdOm5eJQ4geMqKklMWb6GuvdXM4yrCR5fLl8pW/xP8bkVz6stVoMi8zZpsn2tS21M+Y7QzAFX3qst8ulKdrM4ssxW2pp5fmxIV+nfqgcM8T8P9tfeoocayWGX0I2X8dBee6sKd5PgwvsmlhEhe9TadrsKA9XQduTMdRQS2jqpfOdkjqEwvUpfLwEwV5yMx9e3GjiuklRBDs2+aLwFAg9QvsmYCc7n6+eINxv8oY/YqqetW785Gg0ofkbPr56OFaXCsEvyma0BogbcN6Hm0tRCDTeCiQRIqDmPwkmqTm/60ZphEsRmMIuR+TqmoGn6iJsu/BVmAyC/uigjPXqUSu2Ar4pISOH1BFC+XBBVoxyGKq4GpXRzP4YOerRCiidMuE15w8=
  template:
    metadata:
      creationTimestamp: null
      name: mirror
      namespace: common
    type: Opaque
