---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgArYbPufi+v/bCPyZQPGW5Cb3Dv1yWowjrzBWAV1QVv99AlSzfSyaLFCxdzTRfE7p0t2C/CMJ9A+moz2E0+PqD65ZEVkfQBawkdv14NDBiXAXAiiyQNtXmb5RJ2XQ9pXSTdL1ScFnB8Vt41j/XPlSb0cXPAEMpTKsfo3jVrJA68KwMdN7G0igAVyc1YR7st4b1lklx4ZKv/GpW27yyIoXJSubleKt+qKu06yaTqSAf1Byxfmdyqdyu94FT/rIsNo/msH81b9Rne1kCTYwwZhiYF/Yyvn3x4dNaUsejT1o33V5ib9TUywmYyokbLHuxKecgSlm4MmpVKJcXkvxiW53VQj5H+ypmo2XD6Vpnq/IFUi2o2sXx6JXMNV7rCxl/Z+kQErGShzq8OQC9RARCqCGvq6sq9cLx1j25VXvpXqmMJpJovjPLlfjIBvVdq9rkStnlLlWd3n/qzlPwEBzhXFUUOFcSqZOCdB+WTEiqDZbQWERQhEkCM6u+mrDBkhnck3AvqSwWkQYZmqkx1TsFwFrrQK/hCzTTQe679gOIXpwy4ySUab10Cb97buuBctCjB6f9yVHjxDfcTDGyLV1ztCiRAgovH2isHkmkLHCaVcwKDMa8Yp/hlsxGbSqwGxuBeU55Zsw+cP3rpjJmNhgEGbm0tPp9eZfy1y2Byds77v9gJ2IpCfRs9URpTrmAALmzlJqqT0AO4u3QlUCH3jjNatwsHep8axEhoxOq5Ef0ucYc6Hy1WyuFyPODbIRyktBJY9OV0MWmumZKAOVRsc6fVxIWmGWMZ/f+hxMiBC/fucb5t1dB+mbJe5LWrLNx6nLX2L/EuF76ZqEXHUhpD5QSVnw/X9kLQxcxjYOWfJBr87F91FukrDvPu9rluaPN4B8T0M7o0jpLVVIczFi0sC9XnS1lx6Q7zrUss4FoY6p6Q3TV/5FTiNMFTI+OGwlpI0nNEKbYS1vtfs+OXopsuAc4=
  template:
    metadata:
      name: mirror
      namespace: common
    type: Opaque
