---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgB6E60S32G8j2EWGqCgLrK0PtEoo9uKim/giDwvJs9mZvcmMeZ5Qj/8U8e76y/HiMDB0edNY9wKj33rqyRdXpe9W/NLK4+Hv4uccx6WqjbsvFgZRKPSDNUZ8WtuaU/PtC8Myb7Cc/aou3MKSwM/0NKdstNBmcA8De3VjwItAGMEOdqKOje2wQGaF8fUW1uzGzA7p7YrEYQvei7dQ7j9nkCUuipkf4KhfYyszjfAiCP8abJfwbRFCGKM/MGN/RhwnhHZdGhvyvkuIx7sce6bt5syGmSmtXHCNFyO5wSbm5wrsds2mUS/YuO8+gUCKfR38J2AT479D1UqbvC5nCr997h7arqsed30s8euUa3JPjDQpBk5Q9mJ1cDg8P+9X8O/MxFtrMdi+7TJdJ5S0wOIaBareeeHNvNtqn+22g6ACFSMzmV74ZlDn3TRrTdoXedLbB8ivtphcSiql/0MZhyv6LPYuHBNk9gZ5akHh/FSulc/nxSKoDjcFuOnMB2iHhkF6Xq85QtIylZaZctT2iNQgR/XaiRtlYNqfaZ1c41htteV/F3NYP+0EWJ2mgOtw8jjWC62LcYbi9AOVczBHg72HM5sm7HgtYmHz5mESHZnQyIV5LKVi51qXkSULBVrgrFbNeR+dHJjLx8N8KkMNnJ7JDPVhXYa7aesl0SBFp3JVz+oHmF4xoqFs6yJrjMheXNxOlpIu4z0UTQIOUqz06MLZT1hsoAuNmsNGzzDN0D8ntJGq4zks1AxlMFJWZJm1l+Cf4QXX/bxruzIsMc7CgMaY6BC7/85C3UdhhTDZjhN+2NgJ+VY3Igxzypz8biApgGUqwEGTTfJbAHHu3/Q6B2ygv46MwxX69we6nODz6Ipsf33OdXzIS0GuLHxEl/UixK+PnhgymwU8hBW8Nqonk4/Rlu/RZBBGLM5e5/5zLgqaK4EdzppmjmrNi7tEgK6/tkgCuXOFYp0LwADFGBsic8=
  template:
    metadata:
      creationTimestamp: null
      name: mirror
      namespace: common
    type: Opaque
