# SPDX-License-Identifier: Apache-2.0

name: Release Automation

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (semver)"
        required: true

permissions:
  contents: write
  issues: write

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  release:
    name: Release
    runs-on: hiero-mirror-node-linux-medium
    outputs:
      create_pr: ${{ env.CREATE_PR }}
      next_version_snapshot: ${{ env.NEXT_VERSION_SNAPSHOT }}
      pr_title: ${{ env.PR_TITLE }}
      release_branch: ${{ env.RELEASE_BRANCH }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Parse Version
        id: version_parser
        uses: step-security/semver-utils@5bb182a08240146b23b61cc002cb74004377da4b # v5.0.0
        with:
          lenient: false
          version: ${{ github.event.inputs.version }}

      - name: Set Release Environment Variables
        run: |
          PREMINOR_VERSION=${{ steps.version_parser.outputs.inc-preminor }}
          NEXT_VERSION_SNAPSHOT=${PREMINOR_VERSION//-0/-SNAPSHOT}
          RELEASE_BRANCH="release/${{ steps.version_parser.outputs.major }}.${{ steps.version_parser.outputs.minor }}"
          [[ -z "${{ steps.version_parser.outputs.prerelease }}" ]] && \
            VERSION=${{ steps.version_parser.outputs.release }} || \
            VERSION="${{ steps.version_parser.outputs.release }}-${{ steps.version_parser.outputs.prerelease }}"
          RELEASE_TAG="v${VERSION}"

          cat >> $GITHUB_ENV <<EOF
          NEXT_VERSION_SNAPSHOT=$NEXT_VERSION_SNAPSHOT
          RELEASE_BRANCH=$RELEASE_BRANCH
          RELEASE_TAG=$RELEASE_TAG
          VERSION=$VERSION
          EOF

      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.HEDERA_BOT_TOKEN }}

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@c0b4a334b9b72bfaaebec86ef022a78a5b17f828 # v7.0.0
        with:
          git_commit_gpgsign: true
          git_committer_email: ${{ vars.GIT_USER_EMAIL }}
          git_committer_name: ${{ vars.GIT_USER_NAME }}
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v4

      - name: Create and Switch to Release Branch
        run: |
          if ! git ls-remote --exit-code --heads --quiet origin refs/heads/${RELEASE_BRANCH}; then
            git checkout -b ${RELEASE_BRANCH}
            git push -u origin ${RELEASE_BRANCH}

            # create a PR to bump main branch to the next snapshot version
            echo "CREATE_PR=true" >> $GITHUB_ENV
            echo "PR_TITLE=Bump versions for v$NEXT_VERSION_SNAPSHOT" >> $GITHUB_ENV
          else
            git checkout ${RELEASE_BRANCH}
          fi

      - name: Gradle Release
        run: ./gradlew release --newVersion=${{ env.VERSION }}

      - name: Close the Milestone
        if: ${{ steps.version_parser.outputs.prerelease == '' }}
        id: milestone
        uses: step-security/close-milestone@d6e3b63e31f1f869bd3d0403f8cdc1a68f59ab4a # v2.2.2
        with:
          milestone_name: ${{ steps.version_parser.outputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Notes
        if: ${{ steps.version_parser.outputs.prerelease == '' }}
        uses: steven-sheehy/github-changelog-generator@b4174ba12a75add137b35a1e28907d1ac0511f92
        with:
          config-file: .github/release-notes.yml
          milestone: ${{ steps.version_parser.outputs.release }}

      - name: Commit and Tag
        uses: step-security/git-auto-commit-action@749bc1cc775376092cc4227ba537137f445ca7c3 # v7.1.1
        with:
          commit_author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          commit_message: Bump versions for ${{ env.RELEASE_TAG }}
          commit_options: "--no-verify --signoff"
          commit_user_name: ${{ steps.gpg_importer.outputs.name }}
          commit_user_email: ${{ steps.gpg_importer.outputs.email }}
          tagging_message: ${{ env.RELEASE_TAG }}

      - name: Create Github Release
        uses: step-security/release-action@a0d8e0f90f554c15366ca2c9046bf4090d24adbe # v1.21.0
        with:
          bodyFile: changelog.md
          commit: ${{ env.RELEASE_BRANCH }}
          draft: ${{ steps.version_parser.outputs.prerelease == '' }}
          name: ${{ env.RELEASE_TAG }}
          omitBody: ${{ steps.milestone.outputs.milestone_id == '' }}
          prerelease: ${{ steps.version_parser.outputs.prerelease != '' }}
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}

  create_pr:
    name: Create PR
    runs-on: hiero-mirror-node-linux-medium
    needs: release
    if: ${{ needs.release.outputs.create_pr == 'true' }}
    env:
      NEXT_VERSION_SNAPSHOT: ${{ needs.release.outputs.next_version_snapshot }}
      RELEASE_BRANCH: ${{ needs.release.outputs.release_branch }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@c0b4a334b9b72bfaaebec86ef022a78a5b17f828 # v7.0.0
        with:
          git_commit_gpgsign: true
          git_committer_email: ${{ vars.GIT_USER_EMAIL }}
          git_committer_name: ${{ vars.GIT_USER_NAME }}
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v4

      - name: Reset main to release branch
        run: |
          git fetch origin $RELEASE_BRANCH:$RELEASE_BRANCH
          git reset --hard $RELEASE_BRANCH

      - name: Gradle Release for Next Minor Snapshot
        run: ./gradlew release --newVersion=${{ env.NEXT_VERSION_SNAPSHOT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          body: Bump versions for v${{ env.NEXT_VERSION_SNAPSHOT }}
          branch: create-pull-request/${{ env.RELEASE_BRANCH }}
          commit-message: Bump versions for v${{ env.NEXT_VERSION_SNAPSHOT }}
          committer: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          delete-branch: true
          signoff: true
          title: ${{ needs.release.outputs.pr_title }}
          token: ${{ secrets.HEDERA_BOT_TOKEN }}
